### ISSUE TITLE
Disable ssl verifidate

### ISSUE THREAD

**Issue by banana-cakes** [Escape-Technologies/ClairvoyanceNext#17]
Add a flag to disable proxy ssl verifidation

![Screenshot 2023-02-20 070040](https://user-images.githubusercontent.com/124596008/220006734-8c7c6945-5d0e-4d26-bf4b-d24726fd6f5d.png)

**Comment by nohehf** [comment]
Hey @banana-cakes, implemented a `--no-ssl` flag in #18. Please try it and tell me how it went.

**Comment by banana-cakes** [comment]
hey @nohehf , i have no complaints, it's working like a charm.
